In [12]:
import numpy as np

## 1


In [13]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])

In [14]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [15]:
b = np.transpose(a)
b

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [18]:
mean_a=np.mean(b, axis=1)
mean_a

array([2. , 8.4])

## 2

In [19]:
a_centered = a - mean_a

In [20]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## 3

In [23]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]

In [24]:
a_centered_sp

8.0

In [27]:
a.shape

(5, 2)

In [31]:
a_centered_sp = a_centered_sp/(a.shape[0]-1)
a_centered_sp

0.02

## 4

In [34]:
np.cov(a.transpose())[0][1]

2.0